// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilidm.proto

public final class Bilidm {
    private Bilidm() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface DanmakuElemOrBuilder extends
            // @@protoc_insertion_point(interface_extends:DanmakuElem)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         *弹幕dmID
         * </pre>
         *
         * <code>int64 id = 1;</code>
         * @return The id.
         */
        long getId();

        /**
         * <pre>
         *出现时间
         * </pre>
         *
         * <code>int32 progress = 2;</code>
         * @return The progress.
         */
        int getProgress();

        /**
         * <pre>
         *弹幕类型
         * </pre>
         *
         * <code>int32 mode = 3;</code>
         * @return The mode.
         */
        int getMode();

        /**
         * <pre>
         *文字大小
         * </pre>
         *
         * <code>int32 fontsize = 4;</code>
         * @return The fontsize.
         */
        int getFontsize();

        /**
         * <pre>
         *弹幕颜色
         * </pre>
         *
         * <code>uint32 color = 5;</code>
         * @return The color.
         */
        int getColor();

        /**
         * <pre>
         *发送者UID的HASH
         * </pre>
         *
         * <code>string midHash = 6;</code>
         * @return The midHash.
         */
        java.lang.String getMidHash();
        /**
         * <pre>
         *发送者UID的HASH
         * </pre>
         *
         * <code>string midHash = 6;</code>
         * @return The bytes for midHash.
         */
        com.google.protobuf.ByteString
        getMidHashBytes();

        /**
         * <pre>
         *弹幕内容
         * </pre>
         *
         * <code>string content = 7;</code>
         * @return The content.
         */
        java.lang.String getContent();
        /**
         * <pre>
         *弹幕内容
         * </pre>
         *
         * <code>string content = 7;</code>
         * @return The bytes for content.
         */
        com.google.protobuf.ByteString
        getContentBytes();

        /**
         * <pre>
         *发送时间
         * </pre>
         *
         * <code>int64 ctime = 8;</code>
         * @return The ctime.
         */
        long getCtime();

        /**
         * <pre>
         *权重
         * </pre>
         *
         * <code>int32 weight = 9;</code>
         * @return The weight.
         */
        int getWeight();

        /**
         * <pre>
         *动作
         * </pre>
         *
         * <code>string action = 10;</code>
         * @return The action.
         */
        java.lang.String getAction();
        /**
         * <pre>
         *动作
         * </pre>
         *
         * <code>string action = 10;</code>
         * @return The bytes for action.
         */
        com.google.protobuf.ByteString
        getActionBytes();

        /**
         * <pre>
         *弹幕池
         * </pre>
         *
         * <code>int32 pool = 11;</code>
         * @return The pool.
         */
        int getPool();

        /**
         * <pre>
         *弹幕dmID
         * </pre>
         *
         * <code>string idStr = 12;</code>
         * @return The idStr.
         */
        java.lang.String getIdStr();
        /**
         * <pre>
         *弹幕dmID
         * </pre>
         *
         * <code>string idStr = 12;</code>
         * @return The bytes for idStr.
         */
        com.google.protobuf.ByteString
        getIdStrBytes();
    }
    /**
     * Protobuf type {@code DanmakuElem}
     */
    public static final class DanmakuElem extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:DanmakuElem)
            DanmakuElemOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use DanmakuElem.newBuilder() to construct.
        private DanmakuElem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private DanmakuElem() {
            midHash_ = "";
            content_ = "";
            action_ = "";
            idStr_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new DanmakuElem();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private DanmakuElem(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readInt64();
                            break;
                        }
                        case 16: {

                            progress_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            mode_ = input.readInt32();
                            break;
                        }
                        case 32: {

                            fontsize_ = input.readInt32();
                            break;
                        }
                        case 40: {

                            color_ = input.readUInt32();
                            break;
                        }
                        case 50: {
                            java.lang.String s = input.readStringRequireUtf8();

                            midHash_ = s;
                            break;
                        }
                        case 58: {
                            java.lang.String s = input.readStringRequireUtf8();

                            content_ = s;
                            break;
                        }
                        case 64: {

                            ctime_ = input.readInt64();
                            break;
                        }
                        case 72: {

                            weight_ = input.readInt32();
                            break;
                        }
                        case 82: {
                            java.lang.String s = input.readStringRequireUtf8();

                            action_ = s;
                            break;
                        }
                        case 88: {

                            pool_ = input.readInt32();
                            break;
                        }
                        case 98: {
                            java.lang.String s = input.readStringRequireUtf8();

                            idStr_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Bilidm.internal_static_DanmakuElem_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Bilidm.internal_static_DanmakuElem_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Bilidm.DanmakuElem.class, Bilidm.DanmakuElem.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;
        /**
         * <pre>
         *弹幕dmID
         * </pre>
         *
         * <code>int64 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public long getId() {
            return id_;
        }

        public static final int PROGRESS_FIELD_NUMBER = 2;
        private int progress_;
        /**
         * <pre>
         *出现时间
         * </pre>
         *
         * <code>int32 progress = 2;</code>
         * @return The progress.
         */
        @java.lang.Override
        public int getProgress() {
            return progress_;
        }

        public static final int MODE_FIELD_NUMBER = 3;
        private int mode_;
        /**
         * <pre>
         *弹幕类型
         * </pre>
         *
         * <code>int32 mode = 3;</code>
         * @return The mode.
         */
        @java.lang.Override
        public int getMode() {
            return mode_;
        }

        public static final int FONTSIZE_FIELD_NUMBER = 4;
        private int fontsize_;
        /**
         * <pre>
         *文字大小
         * </pre>
         *
         * <code>int32 fontsize = 4;</code>
         * @return The fontsize.
         */
        @java.lang.Override
        public int getFontsize() {
            return fontsize_;
        }

        public static final int COLOR_FIELD_NUMBER = 5;
        private int color_;
        /**
         * <pre>
         *弹幕颜色
         * </pre>
         *
         * <code>uint32 color = 5;</code>
         * @return The color.
         */
        @java.lang.Override
        public int getColor() {
            return color_;
        }

        public static final int MIDHASH_FIELD_NUMBER = 6;
        private volatile java.lang.Object midHash_;
        /**
         * <pre>
         *发送者UID的HASH
         * </pre>
         *
         * <code>string midHash = 6;</code>
         * @return The midHash.
         */
        @java.lang.Override
        public java.lang.String getMidHash() {
            java.lang.Object ref = midHash_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                midHash_ = s;
                return s;
            }
        }
        /**
         * <pre>
         *发送者UID的HASH
         * </pre>
         *
         * <code>string midHash = 6;</code>
         * @return The bytes for midHash.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getMidHashBytes() {
            java.lang.Object ref = midHash_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                midHash_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CONTENT_FIELD_NUMBER = 7;
        private volatile java.lang.Object content_;
        /**
         * <pre>
         *弹幕内容
         * </pre>
         *
         * <code>string content = 7;</code>
         * @return The content.
         */
        @java.lang.Override
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            }
        }
        /**
         * <pre>
         *弹幕内容
         * </pre>
         *
         * <code>string content = 7;</code>
         * @return The bytes for content.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CTIME_FIELD_NUMBER = 8;
        private long ctime_;
        /**
         * <pre>
         *发送时间
         * </pre>
         *
         * <code>int64 ctime = 8;</code>
         * @return The ctime.
         */
        @java.lang.Override
        public long getCtime() {
            return ctime_;
        }

        public static final int WEIGHT_FIELD_NUMBER = 9;
        private int weight_;
        /**
         * <pre>
         *权重
         * </pre>
         *
         * <code>int32 weight = 9;</code>
         * @return The weight.
         */
        @java.lang.Override
        public int getWeight() {
            return weight_;
        }

        public static final int ACTION_FIELD_NUMBER = 10;
        private volatile java.lang.Object action_;
        /**
         * <pre>
         *动作
         * </pre>
         *
         * <code>string action = 10;</code>
         * @return The action.
         */
        @java.lang.Override
        public java.lang.String getAction() {
            java.lang.Object ref = action_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                action_ = s;
                return s;
            }
        }
        /**
         * <pre>
         *动作
         * </pre>
         *
         * <code>string action = 10;</code>
         * @return The bytes for action.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getActionBytes() {
            java.lang.Object ref = action_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                action_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int POOL_FIELD_NUMBER = 11;
        private int pool_;
        /**
         * <pre>
         *弹幕池
         * </pre>
         *
         * <code>int32 pool = 11;</code>
         * @return The pool.
         */
        @java.lang.Override
        public int getPool() {
            return pool_;
        }

        public static final int IDSTR_FIELD_NUMBER = 12;
        private volatile java.lang.Object idStr_;
        /**
         * <pre>
         *弹幕dmID
         * </pre>
         *
         * <code>string idStr = 12;</code>
         * @return The idStr.
         */
        @java.lang.Override
        public java.lang.String getIdStr() {
            java.lang.Object ref = idStr_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                idStr_ = s;
                return s;
            }
        }
        /**
         * <pre>
         *弹幕dmID
         * </pre>
         *
         * <code>string idStr = 12;</code>
         * @return The bytes for idStr.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getIdStrBytes() {
            java.lang.Object ref = idStr_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                idStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeInt64(1, id_);
            }
            if (progress_ != 0) {
                output.writeInt32(2, progress_);
            }
            if (mode_ != 0) {
                output.writeInt32(3, mode_);
            }
            if (fontsize_ != 0) {
                output.writeInt32(4, fontsize_);
            }
            if (color_ != 0) {
                output.writeUInt32(5, color_);
            }
            if (!getMidHashBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, midHash_);
            }
            if (!getContentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
            }
            if (ctime_ != 0L) {
                output.writeInt64(8, ctime_);
            }
            if (weight_ != 0) {
                output.writeInt32(9, weight_);
            }
            if (!getActionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 10, action_);
            }
            if (pool_ != 0) {
                output.writeInt32(11, pool_);
            }
            if (!getIdStrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 12, idStr_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, id_);
            }
            if (progress_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, progress_);
            }
            if (mode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, mode_);
            }
            if (fontsize_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, fontsize_);
            }
            if (color_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, color_);
            }
            if (!getMidHashBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, midHash_);
            }
            if (!getContentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
            }
            if (ctime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(8, ctime_);
            }
            if (weight_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(9, weight_);
            }
            if (!getActionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, action_);
            }
            if (pool_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(11, pool_);
            }
            if (!getIdStrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, idStr_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Bilidm.DanmakuElem)) {
                return super.equals(obj);
            }
            Bilidm.DanmakuElem other = (Bilidm.DanmakuElem) obj;

            if (getId()
                    != other.getId()) return false;
            if (getProgress()
                    != other.getProgress()) return false;
            if (getMode()
                    != other.getMode()) return false;
            if (getFontsize()
                    != other.getFontsize()) return false;
            if (getColor()
                    != other.getColor()) return false;
            if (!getMidHash()
                    .equals(other.getMidHash())) return false;
            if (!getContent()
                    .equals(other.getContent())) return false;
            if (getCtime()
                    != other.getCtime()) return false;
            if (getWeight()
                    != other.getWeight()) return false;
            if (!getAction()
                    .equals(other.getAction())) return false;
            if (getPool()
                    != other.getPool()) return false;
            if (!getIdStr()
                    .equals(other.getIdStr())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
            hash = (53 * hash) + getProgress();
            hash = (37 * hash) + MODE_FIELD_NUMBER;
            hash = (53 * hash) + getMode();
            hash = (37 * hash) + FONTSIZE_FIELD_NUMBER;
            hash = (53 * hash) + getFontsize();
            hash = (37 * hash) + COLOR_FIELD_NUMBER;
            hash = (53 * hash) + getColor();
            hash = (37 * hash) + MIDHASH_FIELD_NUMBER;
            hash = (53 * hash) + getMidHash().hashCode();
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (37 * hash) + CTIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getCtime());
            hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
            hash = (53 * hash) + getWeight();
            hash = (37 * hash) + ACTION_FIELD_NUMBER;
            hash = (53 * hash) + getAction().hashCode();
            hash = (37 * hash) + POOL_FIELD_NUMBER;
            hash = (53 * hash) + getPool();
            hash = (37 * hash) + IDSTR_FIELD_NUMBER;
            hash = (53 * hash) + getIdStr().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Bilidm.DanmakuElem parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Bilidm.DanmakuElem parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Bilidm.DanmakuElem parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Bilidm.DanmakuElem parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Bilidm.DanmakuElem parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Bilidm.DanmakuElem parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Bilidm.DanmakuElem parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Bilidm.DanmakuElem parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Bilidm.DanmakuElem parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Bilidm.DanmakuElem parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Bilidm.DanmakuElem parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Bilidm.DanmakuElem parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Bilidm.DanmakuElem prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code DanmakuElem}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:DanmakuElem)
                Bilidm.DanmakuElemOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Bilidm.internal_static_DanmakuElem_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Bilidm.internal_static_DanmakuElem_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Bilidm.DanmakuElem.class, Bilidm.DanmakuElem.Builder.class);
            }

            // Construct using Bilidm.DanmakuElem.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0L;

                progress_ = 0;

                mode_ = 0;

                fontsize_ = 0;

                color_ = 0;

                midHash_ = "";

                content_ = "";

                ctime_ = 0L;

                weight_ = 0;

                action_ = "";

                pool_ = 0;

                idStr_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Bilidm.internal_static_DanmakuElem_descriptor;
            }

            @java.lang.Override
            public Bilidm.DanmakuElem getDefaultInstanceForType() {
                return Bilidm.DanmakuElem.getDefaultInstance();
            }

            @java.lang.Override
            public Bilidm.DanmakuElem build() {
                Bilidm.DanmakuElem result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Bilidm.DanmakuElem buildPartial() {
                Bilidm.DanmakuElem result = new Bilidm.DanmakuElem(this);
                result.id_ = id_;
                result.progress_ = progress_;
                result.mode_ = mode_;
                result.fontsize_ = fontsize_;
                result.color_ = color_;
                result.midHash_ = midHash_;
                result.content_ = content_;
                result.ctime_ = ctime_;
                result.weight_ = weight_;
                result.action_ = action_;
                result.pool_ = pool_;
                result.idStr_ = idStr_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Bilidm.DanmakuElem) {
                    return mergeFrom((Bilidm.DanmakuElem)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Bilidm.DanmakuElem other) {
                if (other == Bilidm.DanmakuElem.getDefaultInstance()) return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (other.getProgress() != 0) {
                    setProgress(other.getProgress());
                }
                if (other.getMode() != 0) {
                    setMode(other.getMode());
                }
                if (other.getFontsize() != 0) {
                    setFontsize(other.getFontsize());
                }
                if (other.getColor() != 0) {
                    setColor(other.getColor());
                }
                if (!other.getMidHash().isEmpty()) {
                    midHash_ = other.midHash_;
                    onChanged();
                }
                if (!other.getContent().isEmpty()) {
                    content_ = other.content_;
                    onChanged();
                }
                if (other.getCtime() != 0L) {
                    setCtime(other.getCtime());
                }
                if (other.getWeight() != 0) {
                    setWeight(other.getWeight());
                }
                if (!other.getAction().isEmpty()) {
                    action_ = other.action_;
                    onChanged();
                }
                if (other.getPool() != 0) {
                    setPool(other.getPool());
                }
                if (!other.getIdStr().isEmpty()) {
                    idStr_ = other.idStr_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Bilidm.DanmakuElem parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Bilidm.DanmakuElem) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long id_ ;
            /**
             * <pre>
             *弹幕dmID
             * </pre>
             *
             * <code>int64 id = 1;</code>
             * @return The id.
             */
            @java.lang.Override
            public long getId() {
                return id_;
            }
            /**
             * <pre>
             *弹幕dmID
             * </pre>
             *
             * <code>int64 id = 1;</code>
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *弹幕dmID
             * </pre>
             *
             * <code>int64 id = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private int progress_ ;
            /**
             * <pre>
             *出现时间
             * </pre>
             *
             * <code>int32 progress = 2;</code>
             * @return The progress.
             */
            @java.lang.Override
            public int getProgress() {
                return progress_;
            }
            /**
             * <pre>
             *出现时间
             * </pre>
             *
             * <code>int32 progress = 2;</code>
             * @param value The progress to set.
             * @return This builder for chaining.
             */
            public Builder setProgress(int value) {

                progress_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *出现时间
             * </pre>
             *
             * <code>int32 progress = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearProgress() {

                progress_ = 0;
                onChanged();
                return this;
            }

            private int mode_ ;
            /**
             * <pre>
             *弹幕类型
             * </pre>
             *
             * <code>int32 mode = 3;</code>
             * @return The mode.
             */
            @java.lang.Override
            public int getMode() {
                return mode_;
            }
            /**
             * <pre>
             *弹幕类型
             * </pre>
             *
             * <code>int32 mode = 3;</code>
             * @param value The mode to set.
             * @return This builder for chaining.
             */
            public Builder setMode(int value) {

                mode_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *弹幕类型
             * </pre>
             *
             * <code>int32 mode = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearMode() {

                mode_ = 0;
                onChanged();
                return this;
            }

            private int fontsize_ ;
            /**
             * <pre>
             *文字大小
             * </pre>
             *
             * <code>int32 fontsize = 4;</code>
             * @return The fontsize.
             */
            @java.lang.Override
            public int getFontsize() {
                return fontsize_;
            }
            /**
             * <pre>
             *文字大小
             * </pre>
             *
             * <code>int32 fontsize = 4;</code>
             * @param value The fontsize to set.
             * @return This builder for chaining.
             */
            public Builder setFontsize(int value) {

                fontsize_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *文字大小
             * </pre>
             *
             * <code>int32 fontsize = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearFontsize() {

                fontsize_ = 0;
                onChanged();
                return this;
            }

            private int color_ ;
            /**
             * <pre>
             *弹幕颜色
             * </pre>
             *
             * <code>uint32 color = 5;</code>
             * @return The color.
             */
            @java.lang.Override
            public int getColor() {
                return color_;
            }
            /**
             * <pre>
             *弹幕颜色
             * </pre>
             *
             * <code>uint32 color = 5;</code>
             * @param value The color to set.
             * @return This builder for chaining.
             */
            public Builder setColor(int value) {

                color_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *弹幕颜色
             * </pre>
             *
             * <code>uint32 color = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearColor() {

                color_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object midHash_ = "";
            /**
             * <pre>
             *发送者UID的HASH
             * </pre>
             *
             * <code>string midHash = 6;</code>
             * @return The midHash.
             */
            public java.lang.String getMidHash() {
                java.lang.Object ref = midHash_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    midHash_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <pre>
             *发送者UID的HASH
             * </pre>
             *
             * <code>string midHash = 6;</code>
             * @return The bytes for midHash.
             */
            public com.google.protobuf.ByteString
            getMidHashBytes() {
                java.lang.Object ref = midHash_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    midHash_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <pre>
             *发送者UID的HASH
             * </pre>
             *
             * <code>string midHash = 6;</code>
             * @param value The midHash to set.
             * @return This builder for chaining.
             */
            public Builder setMidHash(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                midHash_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *发送者UID的HASH
             * </pre>
             *
             * <code>string midHash = 6;</code>
             * @return This builder for chaining.
             */
            public Builder clearMidHash() {

                midHash_ = getDefaultInstance().getMidHash();
                onChanged();
                return this;
            }
            /**
             * <pre>
             *发送者UID的HASH
             * </pre>
             *
             * <code>string midHash = 6;</code>
             * @param value The bytes for midHash to set.
             * @return This builder for chaining.
             */
            public Builder setMidHashBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                midHash_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object content_ = "";
            /**
             * <pre>
             *弹幕内容
             * </pre>
             *
             * <code>string content = 7;</code>
             * @return The content.
             */
            public java.lang.String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <pre>
             *弹幕内容
             * </pre>
             *
             * <code>string content = 7;</code>
             * @return The bytes for content.
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                java.lang.Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <pre>
             *弹幕内容
             * </pre>
             *
             * <code>string content = 7;</code>
             * @param value The content to set.
             * @return This builder for chaining.
             */
            public Builder setContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                content_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *弹幕内容
             * </pre>
             *
             * <code>string content = 7;</code>
             * @return This builder for chaining.
             */
            public Builder clearContent() {

                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }
            /**
             * <pre>
             *弹幕内容
             * </pre>
             *
             * <code>string content = 7;</code>
             * @param value The bytes for content to set.
             * @return This builder for chaining.
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                content_ = value;
                onChanged();
                return this;
            }

            private long ctime_ ;
            /**
             * <pre>
             *发送时间
             * </pre>
             *
             * <code>int64 ctime = 8;</code>
             * @return The ctime.
             */
            @java.lang.Override
            public long getCtime() {
                return ctime_;
            }
            /**
             * <pre>
             *发送时间
             * </pre>
             *
             * <code>int64 ctime = 8;</code>
             * @param value The ctime to set.
             * @return This builder for chaining.
             */
            public Builder setCtime(long value) {

                ctime_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *发送时间
             * </pre>
             *
             * <code>int64 ctime = 8;</code>
             * @return This builder for chaining.
             */
            public Builder clearCtime() {

                ctime_ = 0L;
                onChanged();
                return this;
            }

            private int weight_ ;
            /**
             * <pre>
             *权重
             * </pre>
             *
             * <code>int32 weight = 9;</code>
             * @return The weight.
             */
            @java.lang.Override
            public int getWeight() {
                return weight_;
            }
            /**
             * <pre>
             *权重
             * </pre>
             *
             * <code>int32 weight = 9;</code>
             * @param value The weight to set.
             * @return This builder for chaining.
             */
            public Builder setWeight(int value) {

                weight_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *权重
             * </pre>
             *
             * <code>int32 weight = 9;</code>
             * @return This builder for chaining.
             */
            public Builder clearWeight() {

                weight_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object action_ = "";
            /**
             * <pre>
             *动作
             * </pre>
             *
             * <code>string action = 10;</code>
             * @return The action.
             */
            public java.lang.String getAction() {
                java.lang.Object ref = action_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    action_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <pre>
             *动作
             * </pre>
             *
             * <code>string action = 10;</code>
             * @return The bytes for action.
             */
            public com.google.protobuf.ByteString
            getActionBytes() {
                java.lang.Object ref = action_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    action_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <pre>
             *动作
             * </pre>
             *
             * <code>string action = 10;</code>
             * @param value The action to set.
             * @return This builder for chaining.
             */
            public Builder setAction(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                action_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *动作
             * </pre>
             *
             * <code>string action = 10;</code>
             * @return This builder for chaining.
             */
            public Builder clearAction() {

                action_ = getDefaultInstance().getAction();
                onChanged();
                return this;
            }
            /**
             * <pre>
             *动作
             * </pre>
             *
             * <code>string action = 10;</code>
             * @param value The bytes for action to set.
             * @return This builder for chaining.
             */
            public Builder setActionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                action_ = value;
                onChanged();
                return this;
            }

            private int pool_ ;
            /**
             * <pre>
             *弹幕池
             * </pre>
             *
             * <code>int32 pool = 11;</code>
             * @return The pool.
             */
            @java.lang.Override
            public int getPool() {
                return pool_;
            }
            /**
             * <pre>
             *弹幕池
             * </pre>
             *
             * <code>int32 pool = 11;</code>
             * @param value The pool to set.
             * @return This builder for chaining.
             */
            public Builder setPool(int value) {

                pool_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *弹幕池
             * </pre>
             *
             * <code>int32 pool = 11;</code>
             * @return This builder for chaining.
             */
            public Builder clearPool() {

                pool_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object idStr_ = "";
            /**
             * <pre>
             *弹幕dmID
             * </pre>
             *
             * <code>string idStr = 12;</code>
             * @return The idStr.
             */
            public java.lang.String getIdStr() {
                java.lang.Object ref = idStr_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    idStr_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <pre>
             *弹幕dmID
             * </pre>
             *
             * <code>string idStr = 12;</code>
             * @return The bytes for idStr.
             */
            public com.google.protobuf.ByteString
            getIdStrBytes() {
                java.lang.Object ref = idStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    idStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <pre>
             *弹幕dmID
             * </pre>
             *
             * <code>string idStr = 12;</code>
             * @param value The idStr to set.
             * @return This builder for chaining.
             */
            public Builder setIdStr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                idStr_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *弹幕dmID
             * </pre>
             *
             * <code>string idStr = 12;</code>
             * @return This builder for chaining.
             */
            public Builder clearIdStr() {

                idStr_ = getDefaultInstance().getIdStr();
                onChanged();
                return this;
            }
            /**
             * <pre>
             *弹幕dmID
             * </pre>
             *
             * <code>string idStr = 12;</code>
             * @param value The bytes for idStr to set.
             * @return This builder for chaining.
             */
            public Builder setIdStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                idStr_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:DanmakuElem)
        }

        // @@protoc_insertion_point(class_scope:DanmakuElem)
        private static final Bilidm.DanmakuElem DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Bilidm.DanmakuElem();
        }

        public static Bilidm.DanmakuElem getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<DanmakuElem>
                PARSER = new com.google.protobuf.AbstractParser<DanmakuElem>() {
            @java.lang.Override
            public DanmakuElem parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DanmakuElem(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DanmakuElem> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<DanmakuElem> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Bilidm.DanmakuElem getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface DmSegMobileReplyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:DmSegMobileReply)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        java.util.List<Bilidm.DanmakuElem>
        getElemsList();
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        Bilidm.DanmakuElem getElems(int index);
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        int getElemsCount();
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        java.util.List<? extends Bilidm.DanmakuElemOrBuilder>
        getElemsOrBuilderList();
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        Bilidm.DanmakuElemOrBuilder getElemsOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code DmSegMobileReply}
     */
    public static final class DmSegMobileReply extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:DmSegMobileReply)
            DmSegMobileReplyOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use DmSegMobileReply.newBuilder() to construct.
        private DmSegMobileReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private DmSegMobileReply() {
            elems_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new DmSegMobileReply();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private DmSegMobileReply(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                elems_ = new java.util.ArrayList<Bilidm.DanmakuElem>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            elems_.add(
                                    input.readMessage(Bilidm.DanmakuElem.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    elems_ = java.util.Collections.unmodifiableList(elems_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Bilidm.internal_static_DmSegMobileReply_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Bilidm.internal_static_DmSegMobileReply_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Bilidm.DmSegMobileReply.class, Bilidm.DmSegMobileReply.Builder.class);
        }

        public static final int ELEMS_FIELD_NUMBER = 1;
        private java.util.List<Bilidm.DanmakuElem> elems_;
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        @java.lang.Override
        public java.util.List<Bilidm.DanmakuElem> getElemsList() {
            return elems_;
        }
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        @java.lang.Override
        public java.util.List<? extends Bilidm.DanmakuElemOrBuilder>
        getElemsOrBuilderList() {
            return elems_;
        }
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        @java.lang.Override
        public int getElemsCount() {
            return elems_.size();
        }
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        @java.lang.Override
        public Bilidm.DanmakuElem getElems(int index) {
            return elems_.get(index);
        }
        /**
         * <code>repeated .DanmakuElem elems = 1;</code>
         */
        @java.lang.Override
        public Bilidm.DanmakuElemOrBuilder getElemsOrBuilder(
                int index) {
            return elems_.get(index);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < elems_.size(); i++) {
                output.writeMessage(1, elems_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < elems_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, elems_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Bilidm.DmSegMobileReply)) {
                return super.equals(obj);
            }
            Bilidm.DmSegMobileReply other = (Bilidm.DmSegMobileReply) obj;

            if (!getElemsList()
                    .equals(other.getElemsList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getElemsCount() > 0) {
                hash = (37 * hash) + ELEMS_FIELD_NUMBER;
                hash = (53 * hash) + getElemsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Bilidm.DmSegMobileReply parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Bilidm.DmSegMobileReply parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Bilidm.DmSegMobileReply parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Bilidm.DmSegMobileReply parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Bilidm.DmSegMobileReply parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Bilidm.DmSegMobileReply parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Bilidm.DmSegMobileReply parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Bilidm.DmSegMobileReply parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Bilidm.DmSegMobileReply parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Bilidm.DmSegMobileReply parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Bilidm.DmSegMobileReply parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Bilidm.DmSegMobileReply parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Bilidm.DmSegMobileReply prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code DmSegMobileReply}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:DmSegMobileReply)
                Bilidm.DmSegMobileReplyOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Bilidm.internal_static_DmSegMobileReply_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Bilidm.internal_static_DmSegMobileReply_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Bilidm.DmSegMobileReply.class, Bilidm.DmSegMobileReply.Builder.class);
            }

            // Construct using Bilidm.DmSegMobileReply.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getElemsFieldBuilder();
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (elemsBuilder_ == null) {
                    elems_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    elemsBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Bilidm.internal_static_DmSegMobileReply_descriptor;
            }

            @java.lang.Override
            public Bilidm.DmSegMobileReply getDefaultInstanceForType() {
                return Bilidm.DmSegMobileReply.getDefaultInstance();
            }

            @java.lang.Override
            public Bilidm.DmSegMobileReply build() {
                Bilidm.DmSegMobileReply result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Bilidm.DmSegMobileReply buildPartial() {
                Bilidm.DmSegMobileReply result = new Bilidm.DmSegMobileReply(this);
                int from_bitField0_ = bitField0_;
                if (elemsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        elems_ = java.util.Collections.unmodifiableList(elems_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.elems_ = elems_;
                } else {
                    result.elems_ = elemsBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Bilidm.DmSegMobileReply) {
                    return mergeFrom((Bilidm.DmSegMobileReply)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Bilidm.DmSegMobileReply other) {
                if (other == Bilidm.DmSegMobileReply.getDefaultInstance()) return this;
                if (elemsBuilder_ == null) {
                    if (!other.elems_.isEmpty()) {
                        if (elems_.isEmpty()) {
                            elems_ = other.elems_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureElemsIsMutable();
                            elems_.addAll(other.elems_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.elems_.isEmpty()) {
                        if (elemsBuilder_.isEmpty()) {
                            elemsBuilder_.dispose();
                            elemsBuilder_ = null;
                            elems_ = other.elems_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            elemsBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getElemsFieldBuilder() : null;
                        } else {
                            elemsBuilder_.addAllMessages(other.elems_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Bilidm.DmSegMobileReply parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Bilidm.DmSegMobileReply) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<Bilidm.DanmakuElem> elems_ =
                    java.util.Collections.emptyList();
            private void ensureElemsIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    elems_ = new java.util.ArrayList<Bilidm.DanmakuElem>(elems_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    Bilidm.DanmakuElem, Bilidm.DanmakuElem.Builder, Bilidm.DanmakuElemOrBuilder> elemsBuilder_;

            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public java.util.List<Bilidm.DanmakuElem> getElemsList() {
                if (elemsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(elems_);
                } else {
                    return elemsBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public int getElemsCount() {
                if (elemsBuilder_ == null) {
                    return elems_.size();
                } else {
                    return elemsBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Bilidm.DanmakuElem getElems(int index) {
                if (elemsBuilder_ == null) {
                    return elems_.get(index);
                } else {
                    return elemsBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder setElems(
                    int index, Bilidm.DanmakuElem value) {
                if (elemsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureElemsIsMutable();
                    elems_.set(index, value);
                    onChanged();
                } else {
                    elemsBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder setElems(
                    int index, Bilidm.DanmakuElem.Builder builderForValue) {
                if (elemsBuilder_ == null) {
                    ensureElemsIsMutable();
                    elems_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    elemsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder addElems(Bilidm.DanmakuElem value) {
                if (elemsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureElemsIsMutable();
                    elems_.add(value);
                    onChanged();
                } else {
                    elemsBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder addElems(
                    int index, Bilidm.DanmakuElem value) {
                if (elemsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureElemsIsMutable();
                    elems_.add(index, value);
                    onChanged();
                } else {
                    elemsBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder addElems(
                    Bilidm.DanmakuElem.Builder builderForValue) {
                if (elemsBuilder_ == null) {
                    ensureElemsIsMutable();
                    elems_.add(builderForValue.build());
                    onChanged();
                } else {
                    elemsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder addElems(
                    int index, Bilidm.DanmakuElem.Builder builderForValue) {
                if (elemsBuilder_ == null) {
                    ensureElemsIsMutable();
                    elems_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    elemsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder addAllElems(
                    java.lang.Iterable<? extends Bilidm.DanmakuElem> values) {
                if (elemsBuilder_ == null) {
                    ensureElemsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, elems_);
                    onChanged();
                } else {
                    elemsBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder clearElems() {
                if (elemsBuilder_ == null) {
                    elems_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    elemsBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Builder removeElems(int index) {
                if (elemsBuilder_ == null) {
                    ensureElemsIsMutable();
                    elems_.remove(index);
                    onChanged();
                } else {
                    elemsBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Bilidm.DanmakuElem.Builder getElemsBuilder(
                    int index) {
                return getElemsFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Bilidm.DanmakuElemOrBuilder getElemsOrBuilder(
                    int index) {
                if (elemsBuilder_ == null) {
                    return elems_.get(index);  } else {
                    return elemsBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public java.util.List<? extends Bilidm.DanmakuElemOrBuilder>
            getElemsOrBuilderList() {
                if (elemsBuilder_ != null) {
                    return elemsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(elems_);
                }
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Bilidm.DanmakuElem.Builder addElemsBuilder() {
                return getElemsFieldBuilder().addBuilder(
                        Bilidm.DanmakuElem.getDefaultInstance());
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public Bilidm.DanmakuElem.Builder addElemsBuilder(
                    int index) {
                return getElemsFieldBuilder().addBuilder(
                        index, Bilidm.DanmakuElem.getDefaultInstance());
            }
            /**
             * <code>repeated .DanmakuElem elems = 1;</code>
             */
            public java.util.List<Bilidm.DanmakuElem.Builder>
            getElemsBuilderList() {
                return getElemsFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    Bilidm.DanmakuElem, Bilidm.DanmakuElem.Builder, Bilidm.DanmakuElemOrBuilder>
            getElemsFieldBuilder() {
                if (elemsBuilder_ == null) {
                    elemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            Bilidm.DanmakuElem, Bilidm.DanmakuElem.Builder, Bilidm.DanmakuElemOrBuilder>(
                            elems_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    elems_ = null;
                }
                return elemsBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:DmSegMobileReply)
        }

        // @@protoc_insertion_point(class_scope:DmSegMobileReply)
        private static final Bilidm.DmSegMobileReply DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Bilidm.DmSegMobileReply();
        }

        public static Bilidm.DmSegMobileReply getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<DmSegMobileReply>
                PARSER = new com.google.protobuf.AbstractParser<DmSegMobileReply>() {
            @java.lang.Override
            public DmSegMobileReply parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DmSegMobileReply(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DmSegMobileReply> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<DmSegMobileReply> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Bilidm.DmSegMobileReply getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_DanmakuElem_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_DanmakuElem_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_DmSegMobileReply_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_DmSegMobileReply_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\014bilidm.proto\"\310\001\n\013DanmakuElem\022\n\n\002id\030\001 \001" +
                        "(\003\022\020\n\010progress\030\002 \001(\005\022\014\n\004mode\030\003 \001(\005\022\020\n\010fo" +
                        "ntsize\030\004 \001(\005\022\r\n\005color\030\005 \001(\r\022\017\n\007midHash\030\006" +
                        " \001(\t\022\017\n\007content\030\007 \001(\t\022\r\n\005ctime\030\010 \001(\003\022\016\n\006" +
                        "weight\030\t \001(\005\022\016\n\006action\030\n \001(\t\022\014\n\004pool\030\013 \001" +
                        "(\005\022\r\n\005idStr\030\014 \001(\t\"/\n\020DmSegMobileReply\022\033\n" +
                        "\005elems\030\001 \003(\0132\014.DanmakuElemb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_DanmakuElem_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_DanmakuElem_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_DanmakuElem_descriptor,
                new java.lang.String[] { "Id", "Progress", "Mode", "Fontsize", "Color", "MidHash", "Content", "Ctime", "Weight", "Action", "Pool", "IdStr", });
        internal_static_DmSegMobileReply_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_DmSegMobileReply_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_DmSegMobileReply_descriptor,
                new java.lang.String[] { "Elems", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}

